spring:
  datasource:
    url: jdbc:h2:mem:carleasedb;INIT=CREATE SCHEMA IF NOT EXISTS LEASE AUTHORIZATION SA
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console.enabled: true
  flyway:
    locations: 'classpath:db/migration'
    enabled: true
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  jackson:
    serialization:
      indent_output: true
  output:
    ansi:
      enabled: DETECT
  security:
    user:
      name: admin
      password: admin
carlease:
  app:
    jwtCookieName: carlease
    jwtSecret: carleaseSecretKey
    jwtExpirationMs: 86400000

logging:
  level:
    root: ERROR
    org.springframework.security: DEBUG
    com.assignment.car: DEBUG
#  pattern:
#    console: %clr(%d{yy-MM-dd E HH:mm:ss.SSS}){blue} %clr(%-5p) %clr(${PID}){faint} %clr(---){faint} %clr([%8.15t]){cyan} %clr(%-40.40logger{0}){blue} %clr(:){red} %clr(%m){faint}%n
#    file: logs/application-debug.log