spring:
  datasource:
    url: jdbc:h2:mem:carleasedb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console.enabled: true
  flyway:
    locations: 'classpath:db/migration'
    enabled: true
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect